---autogenerated

local AI = {}
function AI.Warning() end

function AI.Error() end

function AI.LogProgress() end

function AI.LogEvent() end

function AI.LogComment() end

function AI.RecComment() end

function AI.AddSmartObjectCondition() end

function AI.ExecuteAction() end

function AI.AbortAction() end

function AI.SetSmartObjectState() end

function AI.ModifySmartObjectStates() end

function AI.SmartObjectEvent() end

function AI.GetLastUsedSmartObject() end

function AI.ResetParameters() end

function AI.CreateGoalPipe() end

function AI.BeginGoalPipe() end

function AI.EndGoalPipe() end

function AI.BeginGroup() end

function AI.EndGroup() end

function AI.PushLabel() end

function AI.PushGoal() end

function AI.IsGoalPipe() end

function AI.Signal() end

function AI.NotifyGroup(groupID, sender, notification) end

function AI.FreeSignal() end

function AI.SetIgnorant() end

function AI.BreakEvent( entityID, Vec3 pos, float radius) end

function AI.AddCoverEntity( entityID) end

function AI.RemoveCoverEntity( entityID) end

function AI.SetAssesmentMultiplier() end

function AI.GetGroupCount() end

function AI.GetGroupMember() end

function AI.GetGroupTarget() end

function AI.GetGroupTargetType(groupID) end

function AI.GetGroupTargetThreat(groupID) end

function AI.GetGroupTargetEntity(groupID) end

function AI.GetGroupScriptTable(groupID) end

function AI.GetGroupTargetCount() end

function AI.FindObjectOfType() end

function AI.SoundEvent() end

function AI.VisualEvent() end

function AI.GetSoundPerceptionDescriptor() end

function AI.SetSoundPerceptionDescriptor() end

function AI.GetAnchor() end

function AI.GetFactionOf( entityID) end

function AI.SetFactionOf( entityID, factionName) end

function AI.GetReactionOf() end

function AI.SetReactionOf(factionOne, factionTwo,reaction) end

function AI.GetTypeOf() end

function AI.GetSubTypeOf() end

function AI.GetGroupOf() end

function AI.Hostile() end

function AI.SetRefPointPosition() end

function AI.SetRefPointDirection() end

function AI.SetRefPointRadius() end

function AI.GetRefPointPosition() end

function AI.GetRefPointDirection() end

function AI.GetFormationPointPosition() end

function AI.SetRefShapeName() end

function AI.GetRefShapeName() end

function AI.SetVehicleStickTarget() end

function AI.SetCharacter() end

function AI.SetForcedNavigation() end

function AI.SetAdjustPath() end

function AI.GetHeliAdvancePoint() end

function AI.GetFlyingVehicleFlockingPos() end

function AI.CheckVehicleColision() end

function AI.IntersectsForbidden() end

function AI.IsPointInFlightRegion() end

function AI.IsPointInWaterRegion() end

function AI.GetEnclosingSpace() end

function AI.GetAIObjectPosition() end

function AI.GetBeaconPosition() end

function AI.SetBeaconPosition() end

function AI.GetNearestEntitiesOfType() end

function AI.Event() end

function AI.GetAttentionTargetOf() end

function AI.GetAttentionTargetAIType() end

function AI.GetAttentionTargetType() end

function AI.GetAttentionTargetEntity( entityID) end

function AI.GetAttentionTargetPosition() end

function AI.GetAttentionTargetDistance() end

function AI.GetAttentionTargetDirection() end

function AI.GetAttentionTargetViewDirection() end

function AI.GetAttentionTargetThreat( entityID) end

function AI.GetPotentialTargetCountFromFaction( entityID, factionName) end

function AI.GetPotentialTargetCount( entityID) end

function AI.CreateFormation() end

function AI.AddFormationPointFixed() end

function AI.AddFormationPoint() end

function AI.GetFormationPointClass() end

function AI.GetLeader() end

function AI.UpTargetPriority() end

function AI.DropTarget() end

function AI.ClearPotentialTargets() end

function AI.SetTempTargetPriority() end

function AI.AddAggressiveTarget() end

function AI.UpdateTempTarget() end

function AI.ClearTempTarget() end

function AI.SetExtraPriority() end

function AI.GetExtraPriority() end

function AI.RegisterTargetTrack() end

function AI.UnregisterTargetTrack() end

function AI.SetTargetTrackClassThreat() end

function AI.CreateStimulusEventInRange( targetId, stimulusName, dataScriptTable) end

function AI.SetUnitProperties() end

function AI.GetUnitCount() end

function AI.SetFactionThreatMultiplier() end

function AI.SetLeader() end

function AI.GetStance() end

function AI.SetStance() end

function AI.SetMovementContext(	, entityId,context) end

function AI.ClearMovementContext( entityId,context) end

function AI.AssignPFPropertiesToPathType() end

function AI.AssignPathTypeToSOUser() end

function AI.SetPFProperties() end

function AI.GetTargetType() end

function AI.GetTargetSubType() end

function AI.ChangeFormation() end

function AI.ScaleFormation() end

function AI.SetFormationUpdate() end

function AI.SetPostures( entityId, postures) end

function AI.SetPosturePriority( entityId, postureName, float priority) end

function AI.GetPosturePriority( entityId, postureName) end

function AI.ChangeParameter() end

function AI.GetParameter() end

function AI.ChangeMovementAbility() end

function AI.GetForwardDir() end

function AI.GetNavigationType() end

function AI.GetNearestHidespot() end

function AI.GetDirectAnchorPos() end

function AI.InvalidateHidespot() end

function AI.EvalHidespot() end

function AI.EvalPeek() end

function AI.AddPersonallyHostile( entityID, hostileID) end

function AI.RemovePersonallyHostile( entityID, hostileID) end

function AI.ResetPersonallyHostiles( entityID, hostileID) end

function AI.IsPersonallyHostile( entityID, hostileID) end

function AI.NotifyReinfDone() end

function AI.BehaviorEvent() end

function AI.GetGroupAveragePosition() end

function AI.SetPFBlockerRadius() end

function AI.SetFireMode() end

function AI.SetMemoryFireType() end

function AI.GetMemoryFireType() end

function AI.ThrowGrenade() end

function AI.SetRefPointToGrenadeAvoidTarget() end

function AI.IsAgentInTargetFOV() end

function AI.AgentLookAtPos() end

function AI.ResetAgentLookAtPos() end

function AI.IsAgentInAgentFOV() end

function AI.CreateGroupFormation() end

function AI.SetFormationPosition() end

function AI.SetFormationLookingPoint() end

function AI.SetFormationAngleThreshold() end

function AI.GetFormationPosition() end

function AI.GetFormationLookingPoint() end

function AI.AddCombatClass() end

function AI.SetRefPointAtDefensePos() end

function AI.SetFormationUpdateSight() end

function AI.SetPathToFollow() end

function AI.SetPathAttributeToFollow() end

function AI.GetTotalLengthOfPath() end

function AI.GetNearestPointOnPath() end

function AI.GetPathSegNoOnPath() end

function AI.GetPointOnPathBySegNo() end

function AI.GetPathLoop() end

function AI.SetPointListToFollow() end

function AI.GetNearestPathOfTypeInRange() end

function AI.GetAlertness() end

function AI.GetGroupAlertness() end

function AI.RegisterDamageRegion() end

function AI.GetDistanceAlongPath() end

function AI.IgnoreCurrentHideObject() end

function AI.GetCurrentHideAnchor() end

function AI.FindStandbySpotInShape() end

function AI.FindStandbySpotInSphere() end

function AI.GetProbableTargetPosition() end

function AI.GetObjectRadius() end

function AI.GetEnclosingGenericShapeOfType() end

function AI.IsPointInsideGenericShape() end

function AI.DistanceToGenericShape() end

function AI.ConstrainPointInsideGenericShape() end

function AI.CreateTempGenericShapeBox() end

function AI.SetTerritoryShapeName() end

function AI.NotifySurpriseEntityAction() end

function AI.DebugReportHitDamage() end

function AI.CanMelee() end

function AI.IsMoving() end

function AI.IsEnabled() end

function AI.EnableCoverFire() end

function AI.EnableFire() end

function AI.IsFireEnabled() end

function AI.CanFireInStance() end

function AI.SetUseSecondaryVehicleWeapon() end

function AI.Animation() end

function AI.ProcessBalancedDamage() end

function AI.SetRefpointToAnchor() end

function AI.SetRefpointToPunchableObject() end

function AI.MeleePunchableObject() end

function AI.IsPunchableObjectValid() end

function AI.GetDirLabelToPoint() end

function AI.GetPredictedPosAlongPath() end

function AI.GetBiasedDirection() end

function AI.SetAttentiontarget() end

function AI.RegisterInterestingEntity( entityId, float radius, float baseInterest, aiAction, Vec3 offset, float pause,shared) end

function AI.UnregisterInterestingEntity( entityId) end

function AI.RegisterInterestedActor( entityId, float fInterestFilter, float fAngleInDegrees) end

function AI.UnregisterInterestedActor( entityId) end

function AI.CanMoveStraightToPoint() end

function AI.IsTakingCover() end

function AI.IsMovingToCover() end

function AI.IsMovingInCover() end

function AI.IsCoverCompromised() end

function AI.SetCoverCompromised() end

function AI.IsInCover() end

function AI.SetInCover() end

function AI.StopCommunication( playID) end

function AI.IsOutOfAmmo() end

function AI.IsLowOnAmmo() end

function AI.EnableWeaponAccessory() end

function AI.ResetAgentState( entityId, stateLabel) end

function AI.RegisterTacticalPointQuery() end

function AI.AutoDisable() end

function AI.CheckMeleeDamage() end

function AI.GetTacticalPoints() end

function AI.DestroyAllTPSQueries(  ) end

function AI.CreateQueryFromTacticalSpec( specTable ) end

function AI.GetObjectBlackBoard() end

function AI.GetBehaviorBlackBoard() end

function AI.SetBehaviorVariable( entityId, variableName, value) end

function AI.GetBehaviorVariable( entityId, variableName) end

function AI.GoTo() end

function AI.SetSpeed() end

function AI.SetEntitySpeedRange() end

function AI.SetAlarmed() end

function AI.LoadBehaviors(folderName, extension) end

function AI.LoadCharacters(folderName, tbl) end

function AI.IsLowHealthPauseActive( entityID) end

function AI.GetPreviousBehaviorName( entityID) end

function AI.GetPeakThreatLevel( entityID) end

function AI.GetPeakThreatType( entityID) end

function AI.GetPreviousPeakThreatLevel( entityID) end

function AI.GetPreviousPeakThreatType( entityID) end

function AI.SetContinuousMotion( entityID, continuousMotion) end

function AI.LoadGoalPipes() end

function AI.CheckForFriendlyAgentsAroundPoint( entityID, Vec3 point, float radius) end

function AI.EnableUpdateLookTarget( entityID, bEnable) end

function AI.SetBehaviorTreeEvaluationEnabled( entityID, enabled) end

function AI.UpdateGlobalPerceptionScale( float visualScale, float audioScale) end

function AI.QueueBubbleMessage( entityID, message) end

function AI.SequenceBehaviorReady( entityId ) end

function AI.SequenceInterruptibleBehaviorLeft( entityId ) end

function AI.SequenceNonInterruptibleBehaviorLeft( entityId ) end

function AI.SetCollisionAvoidanceRadiusIncrement( entityId, float radius ) end

function AI.RequestToStopMovement( entityID) end

function AI.GetDistanceToClosestGroupMember( entityIdHandle) end

function AI.IsAimReady( entityIdHandle) end

function AI.AllowLowerBodyToTurn( entityID, bAllowLowerBodyToTurn) end

function AI.GetGroupScopeUserCount( entityIdHandle, groupScopeName) end

function AI.StartModularBehaviorTree( entityIdHandle, treeName) end

function AI.StopModularBehaviorTree( entityIdHandle) end

function AI.SetLastOpResult( entityIdHandle, targetEntityIdHandle) end

return AI
