---autogenerated

local DialogSystem = {}
function DialogSystem.CreateSession( scriptID) end

function DialogSystem.DeleteSession(sessionID) end

function DialogSystem.SetActor(sessionID,actorID, entity) end

function DialogSystem.Play(sessionID) end

function DialogSystem.Stop(sessionID) end

function DialogSystem.IsEntityInDialog( entity) end

return DialogSystem
