---autogenerated

local GameStatistics = {}
function GameStatistics.PushGameScope(scopeID) end

function GameStatistics.PopGameScope() end

function GameStatistics.CurrentScope() end

function GameStatistics.AddGameElement() end

function GameStatistics.RemoveGameElement() end

function GameStatistics.Event() end

function GameStatistics.StateValue() end

return GameStatistics
