---autogenerated

local HitDeathReactions = {}
function HitDeathReactions.OnHit( scriptHitInfo) end

function HitDeathReactions.ExecuteDeathReaction ( reactionParams) end

function HitDeathReactions.ExecuteHitReaction ( reactionParams) end

function HitDeathReactions.EndCurrentReaction() end

function HitDeathReactions.IsValidReaction( validationParams, scriptHitInfo) end

function HitDeathReactions.StartReactionAnim() end

function HitDeathReactions.EndReactionAnim() end

function HitDeathReactions.StartInteractiveAction( szActionName) end

return HitDeathReactions
