---autogenerated

local HUD = {}
function HUD.SetObjectiveStatus(const char* pObjectiveID,status, silent) end

function HUD.SetObjectiveEntity(const char* pObjectiveID,const char* entityName) end

function HUD.ClearObjectiveEntity(const char* pObjectiveID) end

function HUD.AddEntityToRadar( entityId) end

function HUD.RemoveEntityFromRadar( entityId) end

function HUD.AddEntitySilhouette( entityId, float r, float g, float b, float a) end

function HUD.OnGameStatusUpdate(goodBad,msg) end

function HUD.RemoveObjective( entityId) end

return HUD
