---autogenerated

local Inventory = {}
function Inventory.Destroy() end

function Inventory.Clear() end

function Inventory.Dump() end

function Inventory.GetItemByClass(className) end

function Inventory.GetGrenadeWeaponByClass(className) end

function Inventory.HasAccessory(accessoryName) end

function Inventory.GetCurrentItemId() end

function Inventory.GetCurrentItem() end

return Inventory
