---autogenerated

local MatchMaking = {}
function MatchMaking.IsSquadLeaderOrSolo(  ) end

function MatchMaking.CancelSearch(  ) end

function MatchMaking.IsJoiningSession(  ) end

function MatchMaking.IsSessionHost(  ) end

function MatchMaking.IsInSession(  ) end

function MatchMaking.HasGameStarted(  ) end

function MatchMaking.HaveEnoughPlayersToStart(  ) end

function MatchMaking.GetNumPlayersInCurrentSession(  ) end

function MatchMaking.GetNumPlayersInSquad(  ) end

function MatchMaking.GetMaxNumPlayers(  ) end

function MatchMaking.StartSearch(freeSlotsRequired,maxResults, searchParams ) end

function MatchMaking.JoinServer(sessionId ) end

function MatchMaking.CreateServer( sessionParams ) end

function MatchMaking.MergeWithServer(sessionId ) end

function MatchMaking.RequestUpdateCall( float timeToCall ) end

function MatchMaking.MMLog( message, isError ) end

function MatchMaking.GetCurrentRegion(  ) end

function MatchMaking.GetCurrentLanguage(  ) end

function MatchMaking.GetCurrentMatchMakingVersionNum(  ) end

function MatchMaking.GetCurrentPlaylist(  ) end

function MatchMaking.GetCurrentVariant(  ) end

function MatchMaking.GetAvailableDLCs(  ) end

function MatchMaking.GetAverageSkillScore(  ) end

function MatchMaking.GetCurrentPing(  ) end

function MatchMaking.GetCurrentGameMode(  ) end

function MatchMaking.GetCurrentMap(  ) end

return MatchMaking
