---autogenerated

local MaterialEffects = {}
function MaterialEffects.GetEffectId( customName,surfaceIndex) end

function MaterialEffects.GetEffectIdByLibName(  LibName, FGFXName) end

function MaterialEffects.PrintEffectIdByMatIndex( materialIndexchar const* const ,materialIndex) end

function MaterialEffects.ExecuteEffect(effectId, paramsTable) end

return MaterialEffects
