---autogenerated

local Movie = {}
function Movie.PlaySequence(const char *sSequenceName ) end

function Movie.StopSequence(const char* sSequenceName) end

function Movie.AbortSequence(const char* sSequenceName) end

function Movie.StopAllSequences() end

function Movie.StopAllCutScenes() end

function Movie.PauseSequences() end

function Movie.ResumeSequences() end

return Movie
