---autogenerated

local Particle = {}
function Particle.CreateEffect(name, params) end

function Particle.DeleteEffect(name) end

function Particle.IsEffectAvailable(name) end

function Particle.SpawnEffect(effectName, Vec3 pos, Vec3 dir) end

function Particle.SpawnEffectLine(effectName, Vec3 startPos, Vec3 endPos, Vec3 dir, float scale,slices) end

function Particle.SpawnParticles( params, Vec3 pos, Vec3 dir) end

function Particle.CreateDecal( Vec3 pos, Vec3 normal, float size, float lifeTime,textureName) end

function Particle.CreateMatDecal( Vec3 pos, Vec3 normal, float size, float lifeTime,materialName) end

function Particle.Attach() end

function Particle.Detach() end

return Particle
