---autogenerated

local PersistentWorldManager = {}
function PersistentWorldManager.ApplyRadiationToPlayer( eId,radiation) end

function PersistentWorldManager.SavePersistentPlayer( eId) end

function PersistentWorldManager.ResetVehicleSpawner() end

return PersistentWorldManager
