---autogenerated

local Physics = {}
function Physics.SimulateExplosion(explisionTable) end

function Physics.RegisterExplosionCrack(const char *sGeometryFile,nIdMaterial ) end

function Physics.RayWorldIntersection() end

function Physics.RayTraceCheck(Vec3 src,Vec3 dst,skipEntityIdchar const* const ,skipEntityId ) end

function Physics.SamplePhysEnvironment() end

return Physics
