---autogenerated

local PlotSign = {}
function PlotSign.GetPartCount() end

function PlotSign.GetPartId(index) end

function PlotSign.GetPartTypeId(partId) end

function PlotSign.GetPartClassName(partId) end

function PlotSign.GetPartHierarchyParents(partId) end

function PlotSign.CanPackUp(partId) end

function PlotSign.GetMaxHealth(partId) end

function PlotSign.SetDamage(partId, float damage) end

function PlotSign.GetDamage(partId) end

function PlotSign.GetOwnerSteam64Id() end

function PlotSign.GetClanId() end

function PlotSign.AddPartByType(partTypeId, Vec3 pos, Ang3 ang) end

function PlotSign.PackupPart(partId) end

function PlotSign.DeletePart(partId) end

return PlotSign
