---autogenerated

local Sound = {}
function Sound.GetAudioTriggerID( char const* const sTriggerName) end

function Sound.GetAudioSwitchID( char const* const sSwitchName) end

function Sound.GetAudioSwitchStateID( const hSwitchID, char const* const sSwitchStateName) end

function Sound.GetAudioRtpcID( char const* const sRtpcName) end

function Sound.GetAudioEnvironmentID( char const* const sEnvironmentName) end

function Sound.SetAudioRtpcValue( const hRtpcID, float const fValue) end

return Sound
