---autogenerated

local Turret = {}
function Turret.Enable(  ) end

function Turret.Disable(  ) end

function Turret.OnPropertyChange(  ) end

function Turret.OnHit( scriptHitInfo ) end

function Turret.SetStateById(stateId ) end

function Turret.SetFactionToPlayerFaction(  ) end

return Turret
