---autogenerated

local UIAction = {}
function UIAction.ReloadElement( elementName,instanceID ) end

function UIAction.UnloadElement( elementName,instanceID ) end

function UIAction.ShowElement( elementName,instanceID ) end

function UIAction.HideElement( elementName,instanceID ) end

function UIAction.RequestHide( elementName,instanceID ) end

function UIAction.CallFunction( elementName,instanceID, functionName ) end

function UIAction.SetVariable( elementName,instanceID, varName ) end

function UIAction.GetVariable( elementName,instanceID, varName ) end

function UIAction.SetArray( elementName,instanceID, arrayName, values ) end

function UIAction.GetArray( elementName,instanceID, arrayName ) end

function UIAction.GotoAndPlay( elementName,instanceID, mcName,frameNum ) end

function UIAction.GotoAndStop( elementName,instanceID, mcName,frameNum ) end

function UIAction.GotoAndPlayFrameName( elementName,instanceID, mcName, frameName ) end

function UIAction.GotoAndStopFrameName( elementName,instanceID, mcName, frameName ) end

function UIAction.SetAlpha( elementName,instanceID, mcName, float fAlpha ) end

function UIAction.GetAlpha( elementName,instanceID, mcName ) end

function UIAction.SetVisible( elementName,instanceID, mcName, bVisible ) end

function UIAction.IsVisible( elementName,instanceID, mcName ) end

function UIAction.SetPos( elementName,instanceID, mcName, Vec3 vPos ) end

function UIAction.GetPos( elementName,instanceID, mcName ) end

function UIAction.GetScreenPosFromWorld( elementName,instanceID, Vec3 pos /*in/out*/, Vec3 offset /*in/out*/, bScaleMode) end

function UIAction.SetRotation( elementName,instanceID, mcName, Vec3 vRotation ) end

function UIAction.GetRotation( elementName,instanceID, mcName ) end

function UIAction.SetScale( elementName,instanceID, mcName, Vec3 vScale ) end

function UIAction.GetScale( elementName,instanceID, mcName ) end

function UIAction.StartAction( actionName, arguments ) end

function UIAction.EndAction( pTable, disable, arguments ) end

function UIAction.EnableAction( actionName ) end

function UIAction.DisableAction( actionName ) end

function UIAction.RegisterElementListener( pTable, elementName,instanceID, eventName, callback ) end

function UIAction.RegisterActionListener( pTable, actionName, eventName, callback ) end

function UIAction.RegisterEventSystemListener( pTable, eventSystem, eventName, callback ) end

function UIAction.UnregisterElementListener( pTable, callback ) end

function UIAction.UnregisterActionListener( pTable, callback ) end

function UIAction.UnregisterEventSystemListener( pTable, callback ) end

return UIAction
