---autogenerated

local VehicleSeat = {}
function VehicleSeat.Reset() end

function VehicleSeat.GetWeaponId(weaponIndex) end

function VehicleSeat.GetWeaponCount() end

function VehicleSeat.SetAIWeapon( weaponHandle) end

function VehicleSeat.IsFree( actorHandle) end

function VehicleSeat.IsDriver() end

function VehicleSeat.IsGunner() end

function VehicleSeat.GetPassengerId() end

return VehicleSeat
