---autogenerated

local Weapon = {}
function Weapon.SetAmmoCount() end

function Weapon.GetAmmoCount() end

function Weapon.GetClipSize() end

function Weapon.GetAmmoType() end

function Weapon.SetCurrentFireMode(name) end

function Weapon.SupportsAccessory(accessoryName) end

function Weapon.GetAccessory(accessoryName) end

function Weapon.AttachAccessory(className, attach, force) end

function Weapon.SwitchAccessory(className) end

function Weapon.Reload() end

return Weapon
