-- Copyright (C) 2022 Theros [SvalTek|MisModding]
-- 
-- This file is part of MisLuaCompletions.
-- 
-- MisLuaCompletions is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
-- 
-- MisLuaCompletions is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
-- 
-- You should have received a copy of the GNU General Public License
-- along with MisLuaCompletions.  If not, see <http://www.gnu.org/licenses/>.

---@alias tableIndex    number                      `table index`
---@alias filePath      string                      `file path`
---@alias steam64Id     string                      `Players Steam64Id`
